% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Harvard Data Science Capstone: Heart Disease Prediction Model},
  pdfauthor={Andrea De Nardi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Harvard Data Science Capstone: Heart Disease Prediction Model}
\author{Andrea De Nardi}
\date{2025-12-01}

\begin{document}
\maketitle

\subsection{Introduction}\label{introduction}

Cardiovascular diseases (CVDs) are a major public health concern, and
one of the leading causes of death globally. World Health Organization
estimates that 19.8 million people died from CVDs in 2022, representing
about a third of all deaths globally (WHO CVDs, 2022). Given the burden
of CVDs on mortality and healthcare systems, early detection and
targeted care are critical challenges. In this project, we will be using
the UCI ``Cleveland Heart'' dataset (Dua \& Graff, 2019) to train
machine learning models that predict the presence of heart disease from
a set of physiological measures. We will start our analysis by producing
a set of visualization that will help us understand what clinical
measures can successfully predict the risk of heart disease. Our
modeling approach will include simple linear models, classic and
penalized logistic regression, decision trees, and final model selection
via cross-validation and threshold tuning.

\subsubsection{Variables Definition}\label{variables-definition}

Before jumping into our analysis, it is important to define the
variables of the Cleveland Heart Dataset (Kaggle, Heart Disease Dataset
content description):

\begin{itemize}
\item
  Age: Patients Age in years (Numeric)
\item
  Sex: Gender (Male : 1; Female : 0) (Nominal)
\item
  cp: Type of chest pain experienced by patient. This term categorized
  into 4 category.\\
  0 typical angina, 1 atypical angina, 2 non- anginal pain, 3
  asymptomatic (Nominal)
\item
  trestbps: patient's level of blood pressure at resting mode in mm/HG
  (Numerical)
\item
  chol: Serum cholesterol in mg/dl (Numeric)
\item
  fbs: Blood sugar levels on fasting \textgreater{} 120 mg/dl represents
  as 1 in case of true and 0 as false (Nominal)
\item
  restecg: Result of electrocardiogram while at rest are represented in
  3 distinct values\\
  0 : Normal 1: having ST-T wave abnormality (T wave inversions and/or
  ST elevation or depression of \textgreater{} 0.05 mV)\\
  2: showing probable or definite left ventricular hypertrophyby Estes'
  criteria (Nominal)
\item
  thalach: Maximum heart rate achieved (Numeric)
\item
  exang: Angina induced by exercise 0 depicting NO 1 depicting Yes
  (Nominal)
\item
  oldpeak: Exercise induced ST-depression in relative with the state of
  rest (Numeric)
\item
  slope: ST segment measured in terms of slope during peak exercise\\
  0: up sloping; 1: flat; 2: down sloping(Nominal)
\item
  ca: The number of major vessels (0--3)(nominal)
\item
  thal: A blood disorder called thalassemia\\
  0: NULL 1: normal blood flow 2: fixed defect (no blood flow in some
  part of the heart) 3: reversible defect (a blood flow is observed but
  it is not normal(nominal)
\item
  target: It is the target variable which we have to predict 1 means
  patient is suffering from heart disease and 0 means patient is normal.
\end{itemize}

\subsubsection{Data Wrangling}\label{data-wrangling}

Prior to modeling, several preprocessing steps were applied to prepare
the dataset for analysis. The original \texttt{target} variable in the
UCI Cleveland Heart dataset is coded as 0 or 1, indicating the absence
or presence of heart disease. For interpretability and to support
classification workflows in \texttt{caret}, this variable was converted
into a labeled factor with levels \texttt{"no\_disease"} and
\texttt{"disease"}. All categorical predictors (e.g.~chest pain type,
resting ECG results, exercise-induced angina, slope, thal, and the
number of major vessels) were also recoded as factors to ensure they
were correctly handled by algorithms that distinguish between nominal
and numeric inputs. In addition to the categorical target, we created a
secondary numeric outcome variable, \texttt{target\_numeric}, which
retains the original 0/1 encoding. This version of the target was used
for exploratory data analysis tasks such as computing correlations,
where numeric encoding is required. These preprocessing steps ensured
that the dataset was properly structured for both statistical modeling
and exploratory analyses.

\subsection{Analysis}\label{analysis}

\subsubsection{Exploratory Data
Analysis}\label{exploratory-data-analysis}

Let us take a look at the summary statistics of the variables from our
dataset:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(heart)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age            sex      cp         trestbps          chol       fbs    
##  Min.   :29.00   female: 97   1: 23   Min.   : 94.0   Min.   :126.0   0:258  
##  1st Qu.:48.00   male  :206   2: 50   1st Qu.:120.0   1st Qu.:211.0   1: 45  
##  Median :56.00                3: 86   Median :130.0   Median :241.0          
##  Mean   :54.44                4:144   Mean   :131.7   Mean   :246.7          
##  3rd Qu.:61.00                        3rd Qu.:140.0   3rd Qu.:275.0          
##  Max.   :77.00                        Max.   :200.0   Max.   :564.0          
##  restecg    thalach      exang      oldpeak     slope      ca        thal    
##  0:151   Min.   : 71.0   0:204   Min.   :0.00   1:142   0   :176   3   :166  
##  1:  4   1st Qu.:133.5   1: 99   1st Qu.:0.00   2:140   1   : 65   6   : 18  
##  2:148   Median :153.0           Median :0.80   3: 21   2   : 38   7   :117  
##          Mean   :149.6           Mean   :1.04           3   : 20   NA's:  2  
##          3rd Qu.:166.0           3rd Qu.:1.60           NA's:  4             
##          Max.   :202.0           Max.   :6.20                                
##         target    target_numeric  
##  no_disease:164   Min.   :0.0000  
##  disease   :139   1st Qu.:0.0000  
##                   Median :0.0000  
##                   Mean   :0.4587  
##                   3rd Qu.:1.0000  
##                   Max.   :1.0000
\end{verbatim}

The final dataset contains 303 patients, with a mean age of
approximately 54 years (range 29--77). The sample includes 206 males and
97 females. Heart disease is present in 139 patients (46\%) and absent
in 164 patients (54\%), reflecting a reasonably balanced outcome
distribution. Several clinical measurements show substantial
variability, including resting blood pressure (94--200 mmHg),
cholesterol levels (126--564 mg/dl), and maximum heart rate achieved
(71--202 bpm). Categorical predictors such as chest pain type, resting
ECG results, exercise-induced angina, the number of major vessels
observed via fluoroscopy, and thallium stress test results also exhibit
diverse distributions across levels. A small number of missing values is
present in the thal and ca variables, which will need to be handled
before modelling. Overall, the dataset provides a heterogeneous set of
demographic, clinical, and physiological features suitable for
predicting heart disease. Let us now visualize the relationships between
the predictors and the dependent variable.

\textbf{Demographic Factors}

\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-2-1.pdf}
\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-2-2.pdf}

The above histograms shows the distribution of age and sex in our
dataset. The bins have been colored to reflect the diagnosis within each
group (disease = red, no disease = blue). A pattern seems to be emerge,
and to indicate that there is a positive relationship between age and
heart disease diagnosis, although the strength of the link appears to
weaken after 70 years (perhaps due to survivorship bias). In addition,
male seem to be more prone to heart disease than women.

\textbf{Chest Pain and ECG-Related Predictors}

\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-3-1.pdf}
\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-3-2.pdf}
\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-3-3.pdf}
\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-3-4.pdf}

The graphs show that chest pain type \#4 and resting ECG's of type 1
(having ST-T wave abnormality) are associated with higher risks of heart
disease. In addition, the presence of chest pain during exercise (Exang
= 1) and flat or negativs ST Segment Slope are associated with higher
risks of CVDs.

\textbf{Clinical Risk Factors}

\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-4-1.pdf}
\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-4-2.pdf}
\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-4-3.pdf}

The visualizations seem to indicate a moderate positive relationship
between cholesterol levels and disease prevalence (higher summary
statistics for cholesterol levels within the disease group). In
addition, there is a modest difference in heart disease prevalence
between normal and high fasting blood sugar groups (slightly higher for
high FBS group). Maximum heart rate appears to be a solid predictor of
heart disease outcome, with a significantly higher prevalence of heart
disease for lower levels of thalach.

\textbf{Imaging Based Predictors}

\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-5-1.pdf}
\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-5-2.pdf}

The plots show a positive relationship between heart disease proportion
and number of major vessels, as well as a higher heart disease
prevalence among the groups with fixed defect and reversible defect
thalassemia types.

\textbf{Correlations Between Numeric Predictors and Outcome}

\begin{verbatim}
## 
## Attaching package: 'reshape2'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:tidyr':
## 
##     smiths
\end{verbatim}

\includegraphics{heart_disease_model_HSD_capstone_files/figure-latex/unnamed-chunk-6-1.pdf}

The correlation matrix shows that thalach (maximum heart rate) is
moderately negatively correlated with heart disease (−0.42), indicating
that patients achieving lower exercise heart rates are more likely to
have the condition. In contrast, variables such as oldpeak, age, and
resting blood pressure show weak positive correlations with disease
(around 0.15--0.22), suggesting only mild linear associations. Overall,
no single numeric predictor is strongly correlated with the outcome,
supporting the need for multivariate modeling rather than relying on
individual variables.

\subsubsection{Modelling}\label{modelling}

\subsection{Results}\label{results}

\subsection{Conclusion}\label{conclusion}

\subsection{References}\label{references}

\end{document}
